---
- name: deployment
  hosts: node
  
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present
      #  dest:/var/www/html
      
  - name: start apache
    service:
      name: httpd
      state: started
